import type { PartRecord, SupplierRecord } from './types';

export const projectInfo = {
  title: 'Pulse Power Intelligence Desk',
  cluster: 'Pulse power components for advanced energy systems',
  customer: 'Demo program for fusion / pulsed-power adjacent sourcing',
  objective:
    'Translate engineering documents into sourcing-ready part cards, supplier shortlists, RFQ packs, and risk calls.',
};

export const parts: PartRecord[] = [
  {
    id: 'CAP-001',
    name: '25 kV Pulse Discharge Capacitor',
    category: 'HV Capacitor',
    subsystem: 'Main capacitor bank',
    classification: 'Custom',
    summary:
      'Oil-filled pulse capacitor with custom envelope, low ESL target, and life-screening requirement for repetitive discharge service.',
    materials: ['Polypropylene film', 'Aluminum', 'Dielectric oil'],
    targetLeadTimeWeeks: 16,
    annualVolume: 40,
    batchSize: '4-8 units',
    qualityTier: 'Pulse Power / Critical',
    criticalParameters: [
      {
        label: 'Capacitance',
        value: '22 uF +/- 3%',
        level: 'hard',
        rationale: 'Directly sets delivered pulse energy and network tuning.',
      },
      {
        label: 'Equivalent series inductance',
        value: '<= 30 nH',
        level: 'hard',
        rationale: 'Low ESL is required to hit current-rise targets.',
      },
      {
        label: 'Peak current capability',
        value: '>= 180 kA',
        level: 'hard',
        rationale: 'Undersized internal foils or terminations shorten life immediately.',
      },
      {
        label: 'Mounting ear orientation',
        value: 'Preferred existing can footprint',
        level: 'soft',
        rationale: 'A mechanical adapter is acceptable if electrical performance is preserved.',
      },
    ],
    processNeeds: [
      'wound film capacitor assembly',
      'vacuum impregnation',
      'laser or seam welding',
      'partial discharge screening',
      'impulse life test',
    ],
    testNeeds: ['capacitance and dissipation factor report', 'partial discharge report', 'sample impulse life data'],
    qualityNeeds: ['ISO 9001', 'lot traceability', 'partial discharge screening'],
    riskSignals: ['few qualified pulse-capacitor suppliers', 'custom can geometry', 'dielectric life uncertainty'],
    openQuestions: ['Confirm approved dielectric oil family.', 'Confirm whether one spare can is required in the first lot.'],
    documents: [
      { kind: 'drawing', name: 'CAP-001 capacitor can drawing', status: 'available' },
      { kind: 'spec', name: 'Pulse capacitor technical specification', status: 'available' },
      { kind: 'bom', name: 'Capacitor bank BOM line', status: 'available' },
      { kind: 'quality', name: 'Incoming capacitor screening note', status: 'missing' },
      { kind: 'test', name: 'Impulse life acceptance draft', status: 'available' },
    ],
  },
  {
    id: 'SEM-017',
    name: '3.3 kV Fast-Switch Power Module',
    category: 'Power Semiconductor Module',
    subsystem: 'Primary switch rack',
    classification: 'Modified Standard',
    summary:
      'Customized fast-switch module with low-package inductance, controlled screening flow, and repeatable dynamic switching behavior.',
    materials: ['SiC MOSFET dies', 'DBC ceramic', 'Copper baseplate'],
    targetLeadTimeWeeks: 12,
    annualVolume: 60,
    batchSize: '6-12 modules',
    qualityTier: 'Pulse Power / Critical',
    criticalParameters: [
      {
        label: 'Blocking voltage',
        value: '>= 3.3 kV',
        level: 'hard',
        rationale: 'Switch stack margin depends on this floor.',
      },
      {
        label: 'Package stray inductance',
        value: '<= 12 nH',
        level: 'hard',
        rationale: 'Overshoot and turn-off stress grow rapidly above this point.',
      },
      {
        label: 'Thermal resistance',
        value: '<= 0.12 K/W',
        level: 'hard',
        rationale: 'Transient pulse repetition drives junction temperature rise.',
      },
      {
        label: 'Gate connector style',
        value: 'Preferred keyed board header',
        level: 'soft',
        rationale: 'Harness can be adapted if the electrical path is stable.',
      },
    ],
    processNeeds: ['power module packaging', 'die attach', 'wire or ribbon bond', 'burn-in screening', 'dynamic switching test'],
    testNeeds: ['static and dynamic electrical test', 'thermal resistance report', 'burn-in summary'],
    qualityNeeds: ['ISO 9001', 'traceable serial number', 'screening plan approval'],
    riskSignals: ['packaging know-how is concentrated', 'die allocation risk', 'screening requirements may slow NPI'],
    openQuestions: ['Freeze final die set before RFQ release.', 'Confirm whether radiation exposure note is required.'],
    documents: [
      { kind: 'drawing', name: 'SEM-017 package outline drawing', status: 'available' },
      { kind: 'spec', name: 'Fast-switch module specification', status: 'available' },
      { kind: 'bom', name: 'Switch rack BOM row', status: 'available' },
      { kind: 'quality', name: 'Module screening flow note', status: 'available' },
      { kind: 'test', name: 'Dynamic switching acceptance draft', status: 'missing' },
    ],
  },
  {
    id: 'CON-009',
    name: '60 kV Pulse Cable Harness',
    category: 'HV Connector & Cable',
    subsystem: 'Injector pulse feed',
    classification: 'Custom',
    summary:
      'Matched-length high-voltage cable harness with molded stress relief, field-installable ends, and TDR acceptance requirement.',
    materials: ['Silver-plated copper', 'PTFE', 'Silicone'],
    targetLeadTimeWeeks: 8,
    annualVolume: 120,
    batchSize: '10-20 harnesses',
    qualityTier: 'Advanced Hardware',
    criticalParameters: [
      {
        label: 'Dielectric withstand',
        value: '60 kVDC for 5 min',
        level: 'hard',
        rationale: 'Breakdown margin must exceed service condition comfortably.',
      },
      {
        label: 'Propagation delay match',
        value: '+/- 1.5 ns per set',
        level: 'hard',
        rationale: 'Timing skew erodes pulse shape and switch balance.',
      },
      {
        label: 'Minimum bend radius',
        value: '>= 8x cable diameter',
        level: 'hard',
        rationale: 'Over-bend damages dielectric stack and shield integrity.',
      },
      {
        label: 'Connector shell color',
        value: 'Preferred customer standard',
        level: 'soft',
        rationale: 'Can be relabeled if electrical and sealing performance are right.',
      },
    ],
    processNeeds: ['HV cable termination', 'stress cone potting', 'hipot test', 'TDR measurement', 'harness labeling'],
    testNeeds: ['hipot record', 'TDR report', 'continuity and pinout report'],
    qualityNeeds: ['ISO 9001', 'IPC-A-620', 'harness traceability'],
    riskSignals: ['potting-process variation', 'connector supply risk', 'field-repair assumptions unclear'],
    openQuestions: ['Confirm whether a field repair kit is required.'],
    documents: [
      { kind: 'drawing', name: 'CON-009 harness drawing', status: 'available' },
      { kind: 'spec', name: 'HV harness technical note', status: 'available' },
      { kind: 'bom', name: 'Harness BOM row', status: 'available' },
      { kind: 'quality', name: 'Harness workmanship criteria', status: 'available' },
      { kind: 'test', name: 'TDR acceptance note', status: 'available' },
    ],
  },
  {
    id: 'INS-004',
    name: 'Standoff Insulator Set',
    category: 'Insulation & Dielectric',
    subsystem: 'Switch deck supports',
    classification: 'Custom',
    summary:
      'Mixed alumina and G10 support kit with creepage control, precision interface features, and dielectric withstand verification.',
    materials: ['99.5% alumina', 'G10/FR4', 'Epoxy adhesive'],
    targetLeadTimeWeeks: 6,
    annualVolume: 90,
    batchSize: '12-30 sets',
    qualityTier: 'Advanced Hardware',
    criticalParameters: [
      {
        label: 'Creepage distance',
        value: '>= 140 mm',
        level: 'hard',
        rationale: 'Sets contamination tolerance and flashover margin.',
      },
      {
        label: 'Dielectric withstand',
        value: '35 kVDC for 60 s',
        level: 'hard',
        rationale: 'Confirms assembled stack can survive checkout and operation.',
      },
      {
        label: 'Hole true position',
        value: '+/- 0.08 mm',
        level: 'hard',
        rationale: 'Misalignment shifts switch stack loading into ceramic.',
      },
      {
        label: 'Edge break',
        value: '0.2-0.5 mm preferred',
        level: 'soft',
        rationale: 'Could be adjusted by downstream handling if needed.',
      },
    ],
    processNeeds: ['precision ceramic grinding', 'composite machining', 'adhesive bonding', 'dielectric withstand test', 'incoming dimensional sorting'],
    testNeeds: ['dielectric withstand record', 'dimensional report', 'material certification'],
    qualityNeeds: ['ISO 9001', 'lot traceability'],
    riskSignals: ['mixed material stack-up', 'adhesive cure control', 'ceramic breakage during handling'],
    openQuestions: ['Confirm adhesive qualification package requirement.'],
    documents: [
      { kind: 'drawing', name: 'INS-004 insulator drawing', status: 'available' },
      { kind: 'spec', name: 'Insulator material specification', status: 'available' },
      { kind: 'bom', name: 'Support stack BOM row', status: 'available' },
      { kind: 'quality', name: 'Insulator incoming checklist', status: 'missing' },
      { kind: 'test', name: 'Dielectric acceptance matrix', status: 'available' },
    ],
  },
  {
    id: 'ASM-022',
    name: 'Laminated Pulse Busbar Stack',
    category: 'Pulse Power Assembly',
    subsystem: 'Pulse forming network',
    classification: 'Custom',
    summary:
      'Low-inductance laminated busbar assembly with bonded dielectric layers, brazed terminal interfaces, and high-current validation.',
    materials: ['Copper', 'Polyimide film', 'Epoxy dielectric'],
    targetLeadTimeWeeks: 10,
    annualVolume: 36,
    batchSize: '2-6 assemblies',
    qualityTier: 'Pulse Power / Critical',
    criticalParameters: [
      {
        label: 'Loop inductance',
        value: '<= 12 nH',
        level: 'hard',
        rationale: 'Low loop inductance is the whole point of the assembly.',
      },
      {
        label: 'Peak current',
        value: '150 kA for 200 us',
        level: 'hard',
        rationale: 'Joint and laminate design must survive repeated pulse loading.',
      },
      {
        label: 'Dielectric withstand',
        value: '20 kVDC for 60 s',
        level: 'hard',
        rationale: 'Insulation failure would be catastrophic at the subsystem level.',
      },
      {
        label: 'Terminal plating',
        value: 'Tin preferred, bare copper acceptable with rationale',
        level: 'soft',
        rationale: 'Surface finish can be negotiated if contact resistance is controlled.',
      },
    ],
    processNeeds: [
      'laminated busbar fabrication',
      'copper brazing',
      'dielectric bonding',
      'partial discharge screening',
      'thermal cycle test',
    ],
    testNeeds: ['inductance measurement', 'hipot report', 'thermal cycle summary'],
    qualityNeeds: ['ISO 9001', 'traceable serial number', 'special process control'],
    riskSignals: ['few proven low-inductance fabricators', 'joint reliability risk', 'geometry changes can slip in late'],
    openQuestions: ['Confirm whether a spare coupon is required.', 'Freeze terminal plating choice before RFQ release.'],
    documents: [
      { kind: 'drawing', name: 'ASM-022 busbar stack drawing', status: 'available' },
      { kind: 'spec', name: 'Pulse busbar assembly specification', status: 'available' },
      { kind: 'bom', name: 'PFN assembly BOM row', status: 'available' },
      { kind: 'quality', name: 'Busbar process control note', status: 'available' },
      { kind: 'test', name: 'Inductance and hipot acceptance note', status: 'missing' },
    ],
  },
];

export const suppliers: SupplierRecord[] = [
  {
    id: 'SUP-201',
    name: 'Dielec Pulse Components',
    region: 'US Midwest',
    industries: ['Pulse Power', 'Medical Imaging'],
    fitCategories: ['HV Capacitor'],
    processTags: [
      'wound film capacitor assembly',
      'vacuum impregnation',
      'laser or seam welding',
      'partial discharge screening',
      'impulse life test',
    ],
    materialTags: ['Polypropylene film', 'Aluminum', 'Dielectric oil'],
    qualitySystems: ['ISO 9001', 'lot traceability', 'partial discharge screening'],
    stageCapabilities: ['prototype', 'small batch'],
    prototypeLeadTimeWeeks: 14,
    productionLeadTimeWeeks: 20,
    sizeEnvelope: 'pulse capacitors up to 35 kV / 250 kJ class',
    typicalLot: '2-20 units',
    strengths: ['Owns pulse-capacitor winding and impregnation flow', 'Comfortable with low-volume custom cans'],
    cautions: ['Life-test capacity is shared across several programs'],
  },
  {
    id: 'SUP-202',
    name: 'PeakPulse Capacitor Works',
    region: 'EU',
    industries: ['Pulse Power', 'Rail / Traction'],
    fitCategories: ['HV Capacitor', 'Pulse Power Assembly'],
    processTags: [
      'wound film capacitor assembly',
      'vacuum impregnation',
      'partial discharge screening',
      'impulse life test',
      'thermal cycle test',
    ],
    materialTags: ['Polypropylene film', 'Aluminum', 'Dielectric oil', 'Copper'],
    qualitySystems: ['ISO 9001', 'lot traceability', 'special process control'],
    stageCapabilities: ['prototype', 'small batch', 'production'],
    prototypeLeadTimeWeeks: 12,
    productionLeadTimeWeeks: 18,
    sizeEnvelope: 'pulse capacitors and high-energy subassemblies',
    typicalLot: '2-40 units',
    strengths: ['Strong energy-storage know-how', 'Better repeat-build capacity than niche labs'],
    cautions: ['May push toward standard can geometries'],
  },
  {
    id: 'SUP-203',
    name: 'ArcSwitch Power Modules',
    region: 'Asia',
    industries: ['Power Electronics', 'EV / Traction'],
    fitCategories: ['Power Semiconductor Module'],
    processTags: ['power module packaging', 'die attach', 'wire or ribbon bond', 'burn-in screening', 'dynamic switching test'],
    materialTags: ['SiC MOSFET dies', 'DBC ceramic', 'Copper baseplate'],
    qualitySystems: ['ISO 9001', 'traceable serial number', 'screening plan approval'],
    stageCapabilities: ['prototype', 'small batch', 'production'],
    prototypeLeadTimeWeeks: 10,
    productionLeadTimeWeeks: 14,
    sizeEnvelope: 'power modules to 6.5 kV class',
    typicalLot: '5-200 modules',
    strengths: ['Balanced packaging and screening stack', 'Good fit for transition from prototype to repeat build'],
    cautions: ['Custom die allocation still depends on sub-tier planning'],
  },
  {
    id: 'SUP-204',
    name: 'Nexa Packaging Labs',
    region: 'US West',
    industries: ['Power Electronics', 'Industrial Drives'],
    fitCategories: ['Power Semiconductor Module', 'Pulse Power Assembly'],
    processTags: ['power module packaging', 'die attach', 'wire or ribbon bond', 'dynamic switching test', 'thermal cycle test'],
    materialTags: ['SiC MOSFET dies', 'DBC ceramic', 'Copper baseplate', 'Copper'],
    qualitySystems: ['ISO 9001', 'traceable serial number'],
    stageCapabilities: ['prototype', 'small batch'],
    prototypeLeadTimeWeeks: 8,
    productionLeadTimeWeeks: 12,
    sizeEnvelope: 'advanced module packaging and power interconnects',
    typicalLot: '2-40 modules',
    strengths: ['Fast engineering iteration loop', 'Strong package characterization support'],
    cautions: ['Burn-in is limited and may need a controlled partner'],
  },
  {
    id: 'SUP-205',
    name: 'Vector HV Interconnect',
    region: 'US Northeast',
    industries: ['Pulse Power', 'Medical Imaging'],
    fitCategories: ['HV Connector & Cable'],
    processTags: ['HV cable termination', 'stress cone potting', 'hipot test', 'TDR measurement', 'harness labeling'],
    materialTags: ['Silver-plated copper', 'PTFE', 'Silicone'],
    qualitySystems: ['ISO 9001', 'IPC-A-620', 'harness traceability'],
    stageCapabilities: ['prototype', 'production'],
    prototypeLeadTimeWeeks: 6,
    productionLeadTimeWeeks: 10,
    sizeEnvelope: 'high-voltage cable sets to 80 kV class',
    typicalLot: '5-500 harnesses',
    strengths: ['Strong HV termination discipline', 'TDR and hipot are in-house'],
    cautions: ['Connector families should be frozen early to avoid respins'],
  },
  {
    id: 'SUP-206',
    name: 'ShieldLine Cable Technologies',
    region: 'EU',
    industries: ['Aerospace', 'Medical Imaging'],
    fitCategories: ['HV Connector & Cable'],
    processTags: ['HV cable termination', 'stress cone potting', 'hipot test', 'TDR measurement', 'harness labeling'],
    materialTags: ['Silver-plated copper', 'PTFE', 'Silicone'],
    qualitySystems: ['ISO 9001', 'IPC-A-620', 'harness traceability'],
    stageCapabilities: ['prototype', 'small batch', 'production'],
    prototypeLeadTimeWeeks: 7,
    productionLeadTimeWeeks: 11,
    sizeEnvelope: 'shielded and matched-length HV cable systems',
    typicalLot: '5-300 harnesses',
    strengths: ['Good process control on potted HV ends', 'Comfortable with custom labeling and documentation'],
    cautions: ['Cross-border shipping can add schedule noise for urgent builds'],
  },
  {
    id: 'SUP-207',
    name: 'CeramiCore Insulation Systems',
    region: 'US South',
    industries: ['Power Electronics', 'Scientific Equipment'],
    fitCategories: ['Insulation & Dielectric'],
    processTags: ['precision ceramic grinding', 'composite machining', 'adhesive bonding', 'dielectric withstand test', 'incoming dimensional sorting'],
    materialTags: ['99.5% alumina', 'G10/FR4', 'Epoxy adhesive'],
    qualitySystems: ['ISO 9001', 'lot traceability'],
    stageCapabilities: ['prototype', 'production'],
    prototypeLeadTimeWeeks: 5,
    productionLeadTimeWeeks: 8,
    sizeEnvelope: 'insulators and dielectric structures below 1 m',
    typicalLot: '10-500 sets',
    strengths: ['Good blend of ceramic and composite capability', 'Fast dimensional triage on mixed-material kits'],
    cautions: ['Adhesive route needs explicit approval when switching cure systems'],
  },
  {
    id: 'SUP-208',
    name: 'Aurora Ceramic & Composite',
    region: 'EU',
    industries: ['Aerospace', 'Power Electronics'],
    fitCategories: ['Insulation & Dielectric', 'Power Semiconductor Module'],
    processTags: ['precision ceramic grinding', 'composite machining', 'adhesive bonding', 'dielectric withstand test'],
    materialTags: ['99.5% alumina', 'G10/FR4', 'DBC ceramic', 'Epoxy adhesive'],
    qualitySystems: ['AS9100', 'ISO 9001', 'lot traceability'],
    stageCapabilities: ['prototype', 'small batch'],
    prototypeLeadTimeWeeks: 7,
    productionLeadTimeWeeks: 10,
    sizeEnvelope: 'precision dielectric and ceramic support parts',
    typicalLot: '2-80 sets',
    strengths: ['Higher-end process documentation', 'Good option when ceramic quality risk dominates'],
    cautions: ['No dedicated incoming sort line for larger kits'],
  },
  {
    id: 'SUP-209',
    name: 'Laminex Power Distribution',
    region: 'US Southwest',
    industries: ['Industrial Drives', 'Power Electronics'],
    fitCategories: ['Pulse Power Assembly'],
    processTags: ['laminated busbar fabrication', 'copper brazing', 'dielectric bonding', 'thermal cycle test'],
    materialTags: ['Copper', 'Polyimide film', 'Epoxy dielectric'],
    qualitySystems: ['ISO 9001', 'traceable serial number', 'special process control'],
    stageCapabilities: ['prototype', 'small batch', 'production'],
    prototypeLeadTimeWeeks: 9,
    productionLeadTimeWeeks: 13,
    sizeEnvelope: 'laminated busbars and current-distribution stacks',
    typicalLot: '2-200 assemblies',
    strengths: ['Strong repeat-build capability', 'Good copper forming throughput'],
    cautions: ['Partial discharge screening is not in-house'],
  },
  {
    id: 'SUP-210',
    name: 'VoltForge Advanced Assemblies',
    region: 'US West',
    industries: ['Pulse Power', 'Power Electronics'],
    fitCategories: ['Pulse Power Assembly', 'HV Connector & Cable'],
    processTags: [
      'laminated busbar fabrication',
      'copper brazing',
      'dielectric bonding',
      'partial discharge screening',
      'thermal cycle test',
      'harness labeling',
    ],
    materialTags: ['Copper', 'Polyimide film', 'Epoxy dielectric', 'Silver-plated copper'],
    qualitySystems: ['ISO 9001', 'traceable serial number', 'special process control'],
    stageCapabilities: ['prototype', 'small batch'],
    prototypeLeadTimeWeeks: 8,
    productionLeadTimeWeeks: 12,
    sizeEnvelope: 'pulse-power interconnects and current-distribution hardware',
    typicalLot: '1-40 assemblies',
    strengths: ['Best direct adjacency to pulsed-power hardware', 'Can bridge cable and busbar subassemblies'],
    cautions: ['Capacity is limited for larger steady-state programs'],
  },
  {
    id: 'SUP-211',
    name: 'Atlas Motion Controls',
    region: 'Asia',
    industries: ['Industrial Drives', 'Rail / Traction'],
    fitCategories: ['Power Semiconductor Module', 'Pulse Power Assembly'],
    processTags: ['power module packaging', 'dynamic switching test', 'laminated busbar fabrication', 'copper brazing'],
    materialTags: ['DBC ceramic', 'Copper baseplate', 'Copper'],
    qualitySystems: ['ISO 9001', 'traceable serial number'],
    stageCapabilities: ['prototype', 'production'],
    prototypeLeadTimeWeeks: 11,
    productionLeadTimeWeeks: 15,
    sizeEnvelope: 'traction-grade power modules and busbars',
    typicalLot: '5-500 builds',
    strengths: ['Good scale path if the design industrializes', 'Strong copper hardware sourcing network'],
    cautions: ['No approved burn-in line for custom NPI flows'],
  },
  {
    id: 'SUP-212',
    name: 'Helix Energy Interfaces',
    region: 'US Midwest',
    industries: ['Fusion', 'Pulse Power', 'Scientific Equipment'],
    fitCategories: ['HV Connector & Cable', 'Insulation & Dielectric', 'Pulse Power Assembly'],
    processTags: [
      'HV cable termination',
      'dielectric withstand test',
      'laminated busbar fabrication',
      'partial discharge screening',
      'harness labeling',
    ],
    materialTags: ['Copper', 'Polyimide film', 'PTFE', '99.5% alumina'],
    qualitySystems: ['ISO 9001', 'harness traceability', 'special process control'],
    stageCapabilities: ['prototype', 'small batch'],
    prototypeLeadTimeWeeks: 9,
    productionLeadTimeWeeks: 13,
    sizeEnvelope: 'mixed pulse-power interconnects and dielectric hardware',
    typicalLot: '1-30 builds',
    strengths: ['Good fit for fusion-adjacent custom hardware', 'Comfortable with low-volume high-consequence assemblies'],
    cautions: ['Less attractive for high-volume standardized hardware'],
  },
];
